# Generated by Django 4.2.5 on 2023-11-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_product_product_photo_alter_product_time_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='time_minutes',
        ),
        migrations.AddField(
            model_name='product',
            name='upload_time',
            field=models.CharField(blank=True, null=True),
        ),
    ]
