# Generated by Django 4.2.5 on 2023-12-01 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_productimage_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image',
            new_name='product_photo',
        ),
    ]
