# Generated by Django 4.2.6 on 2023-11-10 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_customuser_forget_password_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='forget_password_token',
        ),
    ]
