# Generated by Django 4.2.5 on 2023-12-01 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_rename_image_productimage_product_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='product_photo',
            new_name='product_photos',
        ),
    ]
