# Generated by Django 4.2.6 on 2023-11-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='upload_time',
        ),
        migrations.AddField(
            model_name='product',
            name='upload_date',
            field=models.DateField(auto_now=True),
        ),
    ]
