# Generated by Django 4.2.6 on 2023-11-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_customuser_forget_password_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='used_password_reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
