# Generated by Django 4.2.6 on 2023-11-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_customuser_used_password_reset_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='used_password_reset_token',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
