# Generated by Django 4.2.6 on 2023-12-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_productimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintentry',
            name='target_mail',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='target mail'),
        ),
    ]
