# Generated by Django 4.2.6 on 2023-12-04 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_complaintentry_target_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lostandfoundentry',
            name='category',
        ),
    ]
