# Generated by Django 4.2.5 on 2023-11-30 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_chat_messages_alter_chat_participiants_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('upload_date', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintEntry',
            fields=[
                ('entrybase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.entrybase')),
                ('upvote', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('downvote', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
            ],
            bases=('mainapp.entrybase',),
        ),
    ]
