# Generated by Django 4.2.5 on 2023-11-30 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_entrybase_complaintentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrybase',
            name='topic',
        ),
        migrations.CreateModel(
            name='LostAndFoundEntry',
            fields=[
                ('entrybase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.entrybase')),
                ('topic', models.CharField(max_length=100)),
            ],
            bases=('mainapp.entrybase',),
        ),
    ]
