# Generated by Django 4.2.6 on 2023-12-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_customuser_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostandfoundentry',
            name='category',
            field=models.CharField(blank=True, choices=[('lost', 'Lost'), ('found', 'Found')], max_length=10, null=True),
        ),
    ]
