# Generated by Django 4.2.5 on 2023-11-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_remove_entrybase_topic_lostandfoundentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostandfoundentry',
            name='category',
            field=models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], max_length=10, null=True),
        ),
    ]
