# Generated by Django 4.2.6 on 2023-12-06 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_lostandfoundentry_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='product_photos',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainapp.product'),
        ),
    ]
