# Generated by Django 4.2.6 on 2023-12-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_rename_product_photos_productimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='category',
            field=models.CharField(choices=[('secondhand', 'Secondhand'), ('borrow', 'Borrow'), ('donation', 'Donation'), ('lost', 'Lost'), ('found', 'Found')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='image_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='product_id',
            field=models.IntegerField(null=True),
        ),
    ]
