# Generated by Django 4.2.6 on 2023-12-10 20:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_chat_category_chat_image_url_chat_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintentry',
            name='downvoted_by',
            field=models.ManyToManyField(blank=True, related_name='downvoted_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaintentry',
            name='upvoted_by',
            field=models.ManyToManyField(blank=True, related_name='upvoted_complaints', to=settings.AUTH_USER_MODEL),
        ),
    ]
