# Generated by Django 4.2.6 on 2023-12-12 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_complaintentry_downvoted_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='image_url',
        ),
    ]
