# Generated by Django 4.2.6 on 2023-12-14 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_remove_chat_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_message', 'New Message'), ('upvoted_complaint', 'Upvoted Complaint'), ('downvoted_complaint', 'Downvoted Complaint')], max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('related_item_id', models.IntegerField(blank=True, null=True)),
                ('related_item', models.CharField(blank=True, choices=[('PRODUCT', 'Product'), ('COMPLAINT', 'ComplaintEntry'), ('LOSTFOUND', 'LostAndFoundEntry'), ('CHAT', 'Chat')], max_length=100, null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
