# Generated by Django 4.2.6 on 2023-12-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_alter_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('book', 'Book'), ('household', 'Household'), ('clothing_accessories', 'Clothing & Accessories'), ('toys_games', 'Toys & Games'), ('sports', 'Sports'), ('art', 'Art'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
