# Generated by Django 4.2.6 on 2023-12-16 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def create_onlineusermodel(apps, schema_editor):
    CustomUser = apps.get_model('mainapp', 'CustomUser')
    OnlineUserModel = apps.get_model('mainapp', 'OnlineUserModel')
    for user in CustomUser.objects.all():
        OnlineUserModel.objects.create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_customuser_is_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineUserModel',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_online', models.BooleanField(default=False)),
            ],
        ),
        migrations.RunPython(create_onlineusermodel),
        migrations.RemoveField(
            model_name='customuser',
            name='is_online',
        ),
    ]
